[project]
name = "p-transformer-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.50.0",
    "tiktoken>=0.12.0",
    "torch>=2.9.0",
]
